ALTER TABLE clients ADD COLUMN email_subject TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN email_body TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN email_cc TEXT NOT NULL DEFAULT '';
